app = 'fly-smokescreen-floral-grass-3594'

[build]

[[services]]
protocol = 'tcp'
internal_port = 3000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 80

[[vm]]
size = 'shared-cpu-1x'

[metrics]
port = 9810
path = '/metrics'
